name = "XSFreader"
uuid = "a1cc6ac7-c4a6-45b2-8bc3-77ae002c558d"
authors = ["Yuki Nagai <cometscome@gmail.com> and contributors"]
version = "0.0.1"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
